### ISSUE TITLE
"Guys"

### ISSUE THREAD

**Issue by omninonsense** [apeiros/ruby-community#27]
## Opinion

In some languages the term could be considered exclusive, but in English it's a synonym "people." If you refer the male subset in a a mixed gender group, you'd use "dudes," "boys," or "men"; using "guys" would imply the whole room. The traditional use for the word was replaced. Same thing happened to terms like "gay", "mate" (in British English), and many other words that are used colloquially today. Please keep up with the times, _people_.

I do understand why some might be offended, and I don't have a problem not using a different word for addressing the channel as a whole, since I don't want to cause anyone discomfort.

If I got offended each time someone said used the term "gay" as a synonym for "homosexual," simply because I consider "gay" to be a very narrow subculture and a collection of cliché traits, then I'd be offended all the time, but I choose not to be because I can deduce the intent without much intellectual overhead.

However, at the same time policing free speech because some people _choose_ to be offended (yes, it's a choice to be offended in this case) by generally accepted colloquialism, is unjust towards everyone else. If we keep policing free speech like this, we're causing a different type of discomfort&mdash;one where everyone's walking on eggshells out of fear of being called out for being degrading, ignorant, or disrespectful. We're creating an oppressive environment.

Why should someone's discomfort (namely, the "I am not one of the guys" group's) be preferred over everyone else's (people who want to hold a conversation without being called out for being a shit-ass-fucking-person in front of everyone for using common speech patterns and colloquialisms)? If someone used the word in a derogatory manner, was being mean (name calling), racist (using racial slur), sexist (misogyny or misandry) or jingoists, I'd be all for warning them or disciplining them. 

Yes, women are often treated badly in tech, but since nobody is treating anyone disrespectfully (in this case), those issues people are experiencing when they see the word "guys" are personal issues, not channel issue.

---

Now, here's _the_ (I can't stress this enough) problem I have with this whole issue: This is a ruby community, not a social-politics-debate community. If you feel excluded by "guys" then don't help that person. Who gives a fuck?

I also consider both facts useless. The hangman is more useful!

However, since it's unlikely anyone actually cares about the opinion, here is a proposed...
## Solution

Let's keep the `?guys` and `?guys2` facts. I don't care about them, I just care that they cause so much shit for trivialities. However, as it currently stands they're detrimental to the above issue for a few reasons. I'll address both separately.
### `?guys` fact

> You probably don't mean to exclude, but not everyone relates to being "one of the guys". Maybe consider using "folks", "all", "y'all", or "everyone" instead?
> <cite>&mdash; ruboto</cite>

---

> You probably don't mean to exclude, but not everyone relates to being "one of the guys".

Of course they didn't mean it; this structure looks passive aggressive, and feels accusatory. It depends on the person reading them, but considering they're being called out for something, it's more common they'll read it with a negative connotation.

> Maybe consider using "folks", "all", "y'all", or "everyone" instead?

This seems very... For a lack of a better word: _snide_. I can't be certain, but I think the question-mark at the end makes it feel snide. The sentence wouldn't be snide on it own probably, but we need to consider the first sentence invokes a negative mood in the person reading it. Another reason why it seems snide, is because it offers you choices: <q>Can't you come up with something gender neutral, idiot?</q>. Moreover, the word <q>consider</q> might sounds like you're calling someone inconsiderate

The alternative I propose:

> Please using a more gender neutral way of addressing the channel as a whole. Some parties feel excluded by the term "guys". Thank you for being respectful! 

The reasoning behind <q>Please _use_</q> is: it is demanding, but polite and soft, but it doesn't imply they're inconsiderate. And <q>Thank you for being respectful!</q> is likely cause a positive, because you thanked them for improving in advance (and might even prompt an apology), and they will feel gently pushed into opting in.
### `?guys2` fact

> it doesn't matter if it’s "normal"/gender neutral to say "guys" in your idiolect. "You guys" to refer to a mixed group is erasure. All we ask from you is to be a decent channel member and respect that. If you want to further discuss this, join #ruby-offtopic.
> <cite>&mdash; ruboto</cite>  

---

> it doesn't matter if it’s "normal"/gender neutral to say "guys" in your idiolect.

Yes, yes it does matter. Belittling the way someone speaks is rude,. It's a matter of origin, culture, and style; respect it even if you don't like it (see what I did there?).

> "You guys" to refer to a mixed group is erasure.

They're being accused, again...

> All we ask from you is to be a decent channel member and respect that.

...and again, because it implies they're not decent.

I would only leave this as part of `?guys2`

> If you want to further discuss this, join #ruby-offtopic.

Even though, this shouldn't even be up for discussion. So&mdash;better yet&mdash;just use `?ot`, because it's apt:

> this seems to be off-topic. Please move your discussion to #ruby-offtopic, to keep this channel free for Ruby related problems. Thanks!

And then take a per-person approach on explaining why this exists. Not everyone reacts or complains about the same thing here, and not everyone sees things the same, so we can't use one simple fact/summary for a social issue as complex as this.

Explain that this exists to make everyone feel comfortable. Also, explain that everyone would be grateful if they dropped the subject and refrained from using over-generalised phrases, now that they know some people are being hurt by them.

I still don't think this is ideal, but at least it might mitigate the number of times this (both the word "guys" and the fact `?guys`) is an issue.

**Comment by sevenseacat** [comment]
I think you should choose not to be offended by our attempts at inclusivity.

**Comment by omninonsense** [comment]
@sevenseacat I apologise if that is how my post made you feel. I am not opposed to (or offended by)  having an inclusive environment at all.  On the contrary, I'm all for it! 

However I feel like governing *very common* speech patterns and phrases because a handful of people decided to be offended by them, is not a step in that direction. All this has done so far is instigate unnecessary discussions. 

I understand why some people  might not like it, but they exclude themselves, there's no need to create rules and bot facts for personal feelings.

"Guys" isn't a derogatory slang or term for any group, nor is it meant to actively exclude. People who casually use "Guys" in a sentence are the victims here because they're being "shamed" for sexism when it is in fact not sexism on their part. Of-fucking-course will they have a harsh reaction and become defensive when you accuse them of something as serious as that, and no phrasing of the fact will ever help with that.

**Comment by omninonsense** [comment]
I'd also like to add, at the risk of sounding like a total dick: this whole affair  feels like some stupid tumblr-feminism (which is were different from *actual* feminism) movement that started on a 12 year old hipster girl's  anti-patriachary post on a blog that screens "I want your attention!" and doesn't seem legitimate to me at all. I've seen no real arguments in favour of this apart from "some people feel excluded because they don't feel like one of the guys" which is in my most humble opinion *utter bullocks*

Furthermore, I feel like it's also borderline trolling of the whole channel,  by a small group of people who claim to be offended by it.

If you're being addressed as a "guy" grab your frigging lady parts, woman up and tell them you're a woman and that you didn't like being addressed as a guy. Don't hide behind ops.

Also: As a male pro-feminism movement person, my advice to everyone offended by "guys" is: Feminism is not about being a little bitch. 

# It is just *so damn* surplus.

**Comment by sevenseacat** [comment]
No-one's "hiding behind ops". I put that message there. It's been modified since I added it, but I originally put it there. I am a woman, and an op. 

The fact that you assumed otherwise is part of the problem.

You don't get to choose how other people interpret and feel when reading your words. Just because speech patterns are "very common" doesn't mean they're good, or right, or can't be improved. It's a simple message alerting people, most of whom aren't aware (and are thankful for us telling them), that "guys" isn't in fact as ungendered as they thought it was.

http://jvns.ca/blog/2013/12/27/guys-guys-guys/ might be worth your reading, especially the number of both men and women who don't feel that the word is gender-neutral.

**Comment by omninonsense** [comment]
The fact that you are or aren't an op is mostly irrelevant to my "hiding behind ops." It was baldy phrased, but what I want was "hiding behind an annoying rule that doesn't need to exist." 

The blog post was interesting. Especially the bits about Java/Python. Although, I am a bit unsure the survey can be used as a reference. Also in light of the survey, if someone referenced a person as a he and I knew that the person doesn't identify as a he), I'd be the first to tell someone not to make no such assumptions; "Guys" used to address the channel just isn't the same.

Just to clarify, I don't mind *you* or *anyone else* telling people that they ought not to use "Guys." I just feel it's an unnecessary rule.

I'm not really in the habit of using it, so it doesn't really affect me. However, I am annoyed by by the mild unrighteous and oppressive nature of the rule.

Further, people who think it's gender neutral will keep using it and it will start discussions on the channels. People who choose to be offended by it well remain offended, and we're at a stalemate. We shouldn't have rules like this. Not to mention is bizarrely specific that someone could argue they feel discriminated—why is there not a rule to protect thei feelings? Then we'll end up having so many rules it'll be hard to keep track of them.

Also, this is kinda covered by 1.1 and 2.1 (on the rules page) rules. If it bothers you, just tell them.

Also, in the spirit of community, we should just have a poll and post it in the topic to see how many people are in favour and how many people are against the rule.

**Comment by apeiros** [comment]
First, to get this off straight away: you do _not_ have free speech in #ruby. There are things you are not allowed to say and which will get you outright banned. Examples include racism and insults. See http://ruby-community.com/pages/user_rules
Second: nobody got kicked, muted or banned for using "guys". They got reminded that the term is erasing, and are friendly asked to change _a single word in their vocabulary_. Not so fucking difficult.
"Also: As a male pro-feminism movement person" - bullshit. Your whole riot about "How dare you tell me to change! Women who feel excluded by my behavior have to blame themselves!" is you being an egocentric ass and not the least somebody pro equal treatment of women.

We will continue to work on the wording we use, as not to trigger the obviously very tender feelings of some men. But other than that, we'll keep this up. If this means we lose some men who put the usage of one word over not erasing half the population, then know what? Gladly. Those people are toxic and the less we have of them, the better.

**Comment by omninonsense** [comment]
> First, to get this off straight away: you do not have free speech in #ruby. There are things you are not allowed to say and which will get you outright banned. Examples include racism and insults.

I'm not a lawyer, but I think free speech and hate speech are not the same. On that note, free speech doesn't really apply to this context anyway. I admit to have misused the term. 

> They got reminded that the term is erasing, and are friendly asked to change a single word in their vocabulary. Not so fucking difficult.

It's a matter of principle, not whether it's hard or not. Also, I vaguely remember someone saying in OT channel that they considered muting a user because the re-used "guys" because the user was "likely trolling" (irrelevant if they were or weren't, *apparently*). 

> "Also: As a male pro-feminism movement person" - bullshit. Your whole riot about "How dare you tell me to change! Women who feel excluded by my behavior have to blame themselves!" is you being an egocentric ass and not the least somebody pro equal treatment of women.

There's no equality involved regarding the butchering of an innocent word. *If anything* they're getting *special treatment* not equal treatment in this whole issue.

Other than that, I don't even have the habit of using guys when greeting people; if I do use it, it's on extremely rare occasions. So, no this was not about me being egocentric. 

And there's no need to be fucking rude just because you disagree with me.

> We will continue to work on the wording we use, as not to trigger the obviously very tender feelings of some men

This is outright hypocrisy. Why are you so bashful of feelings of men, but take such delicate care of women's?

> If this means we lose some men who put the usage of one word over not erasing half the population, then know what? Gladly. Those people are toxic and the less we have of them, the better.

This is hyperbolic. Nobody wants to erase women? The only toxic thing here is this ridiculous rule!

**Comment by apeiros** [comment]
Insults are not hate speech and still get you banned.
Offtopic talk does not even have to be vitriolic but can get you banned if you're asked to move it to another channel and don't follow that request.
And if you troll, you get banned too. The tool you use to troll is irrelevant. And yes, trolling is poorly defined. That's sadly in the nature (and to a degree the aim) of it.

As for the rest, I'd just repeat myself, so I'll leave it at what I've already written.
