### ISSUE TITLE
code documentation a la ri in ruboto?

### ISSUE THREAD

**Issue by tamouse** [apeiros/ruby-community#29]
Would it be helpful / useful to have ruboto provide snippets of the documentation _a la_ `ri` ? I know I'm using it in `pry` all the time, and having to run off to link to a snippet online to show someone sometimes is a pain.

**Comment by jhass** [comment]
I think that'll be too verbose for the most part. There's some plan to integrate https://github.com/adaedra/cinch-rubydoc though

**Comment by tamouse** [comment]
That would be cool; it's really what I was envisioning, not putting all the doc _into_ ruboto. What a headache that would be for maintenance.
