### ISSUE TITLE
ruby-community organisation

### ISSUE THREAD

**Issue by adaedra** [apeiros/ruby-community#36]
We're starting to have some projects related to ruby-community (the website, the rdoc plugin, ...) and we may expect some more starting if we get things moving and great ideas (we will, right? :wink: )

To group these projects, and the contributors to the community (importanter!), we could consider having a github organisation. That would be the one-and-only stop for all ruby-community related projects.

**Comment by jhass** [comment]
Organization actually exists now, should we start moving stuff?
